{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "#File description & paths to csv's\n",
    "\"\"\"\n",
    "Code is divided into the following sections:\n",
    "1. Import data & create dataframes:\n",
    "    -credit_records_o contains credit_records from csv file, same structure as in the file (long form)\n",
    "    -application_records_o contains data from application csv, file same structure as in the file\n",
    "    -credit_records_t is wide form of credit_records_o \n",
    "2. Prepare data in application records (i.e. fill in blanks in occupation type, standardize values and more)\n",
    "3. Enrich credit data with start, end, duration, count of individual statues (0_count, 1_count... 5 ratio) and count all statuses (all_late_count),\n",
    "ratio of individual status (0_ratio, 1_ratio... 5_ratio) and all late statuse ratio (all_later_ratio)\n",
    "    - credit_records_t_label\n",
    "4. Enrich credit data with Active & TOTAL_STATUS & GOOD_BAD CLIENT measures calculated wiht Mateusz method\n",
    "5. Merge app & labelled credit data and calculate bins for discrete variables (birth date, employment date & amount income)\n",
    "    - app_and_credit_label_2\n",
    "6. Functions for GUI in IPWIDGET that take & store user input from ipywidgets\n",
    "5. \n",
    "\"\"\"\n",
    "\n",
    "#read script location and look for folder called data in which there should be files to import\n",
    "import os\n",
    "data_dir=os.path.join(os.path.abspath(''),\"data\")\n",
    "path_to_credit_records_csv=os.path.join(data_dir,\"credit_record.csv\")\n",
    "path_to_application_records_csv=os.path.join(data_dir,\"application_record.csv\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Final version of app for exploring clients default probability"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "### 1. Import of data & dataframe def \n",
    "import pandas as pd\n",
    "\n",
    "#create credit_records_o from data in csv\n",
    "file=open(path_to_credit_records_csv) \n",
    "credit_records_o=pd.read_csv(file) \n",
    "file.close()\n",
    "\n",
    "#create application_records_o from data in csv\n",
    "file=open(path_to_application_records_csv) \n",
    "application_records_o=pd.read_csv(file) \n",
    "file.close()\n",
    "\n",
    "#create wide version of credit_records\n",
    "credit_records_t=pd.pivot(credit_records_o, index='ID',columns='MONTHS_BALANCE',values='STATUS') \n",
    "credit_records_t = credit_records_t[credit_records_t.columns.sort_values(ascending=False)] #reorder months balance column in descending order"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "### 2. Application Data Preparation Asia\n",
    "\n",
    "import numpy as np\n",
    "application_records_t=application_records_o.copy()\n",
    "application_records_t.drop(\"FLAG_MOBIL\", axis=1, inplace=True) #dropping as its 1 across all rows\n",
    "application_records_t[\"FLAG_OWN_CAR\"].replace([\"Y\",\"N\"],[\"1\",\"0\"],inplace=True) #standardize to same format as other flags i.e. 1 for True and 0 for False\n",
    "application_records_t[\"FLAG_OWN_REALTY\"].replace([\"Y\",\"N\"],[\"1\",\"0\"],inplace=True) #standardize to same format as other flags i.e. 1 for True and 0 for False\n",
    "application_records_t[\"FLAG_OWN_CAR\"]=application_records_t[\"FLAG_OWN_CAR\"].astype(int) #standardize to int format\n",
    "application_records_t[\"FLAG_OWN_REALTY\"]=application_records_t[\"FLAG_OWN_REALTY\"].astype(int) #standardize to int format\n",
    "application_records_t[\"OCCUPATION_TYPE\"].fillna(value=\"Not provided\", inplace=True) #fill in blanks in occupation type\n",
    "\n",
    "# files categorizing\n",
    "conditions=[\n",
    "    (application_records_t[\"CNT_CHILDREN\"] == 0),\n",
    "    (application_records_t[\"CNT_CHILDREN\"] == 1),\n",
    "    (application_records_t[\"CNT_CHILDREN\"] == 2) & (application_records_t[\"CNT_CHILDREN\"] ==3 ),\n",
    "    (application_records_t[\"CNT_CHILDREN\"] >3)\n",
    "]\n",
    "values=[\"No children\", \"1 child\", \"2-3 children\", \"Many children\"]\n",
    "application_records_t[\"CNT_CHILDREN_CATEGORIZED\"]=np.select(conditions,values)\n",
    "conditions1=[\n",
    "    (application_records_t[\"CNT_FAM_MEMBERS\"] == 1),\n",
    "    (application_records_t[\"CNT_FAM_MEMBERS\"] == 2),\n",
    "    (application_records_t[\"CNT_FAM_MEMBERS\"] == 3),\n",
    "    (application_records_t[\"CNT_FAM_MEMBERS\"] == 4),\n",
    "    (application_records_t[\"CNT_FAM_MEMBERS\"] >4)\n",
    "]\n",
    "values1=[\"1 person household\", \"couple\", \"2+1\", \"2+2\",\"big family\"]\n",
    "application_records_t[\"CNT_FAM_MEMBERS_CATEGORIZED\"]=np.select(conditions1,values1)\n",
    "conditions2=[\n",
    "    (application_records_t[\"AMT_INCOME_TOTAL\"] <= 50000),\n",
    "    (application_records_t[\"AMT_INCOME_TOTAL\"] > 50000)&(application_records_t[\"AMT_INCOME_TOTAL\"]<=100000),\n",
    "    (application_records_t[\"AMT_INCOME_TOTAL\"] > 100000)& (application_records_t[\"AMT_INCOME_TOTAL\"]<=200000),\n",
    "    (application_records_t[\"AMT_INCOME_TOTAL\"] > 200000),\n",
    "]\n",
    "values2=[\"very low income\", \"medium income\", \"high income\", \"very high income\"]\n",
    "application_records_t[\"AMT_INCOME_TOTAL_CATEGORIZED\"]=np.select(conditions2,values2)\n",
    "conditions3=[\n",
    "    (application_records_t[\"DAYS_BIRTH\"] < 0 ) & (application_records_t[\"DAYS_BIRTH\"]>=-7300),\n",
    "    (application_records_t[\"DAYS_BIRTH\"] < -7300) & (application_records_t[\"DAYS_BIRTH\"]>=-10950),\n",
    "    (application_records_t[\"DAYS_BIRTH\"] < -10950) & (application_records_t[\"DAYS_BIRTH\"]>=-14600),\n",
    "    (application_records_t[\"DAYS_BIRTH\"] < -14600) & (application_records_t[\"DAYS_BIRTH\"]>=-18250),\n",
    "    (application_records_t[\"DAYS_BIRTH\"] < -18250) & (application_records_t[\"DAYS_BIRTH\"]>=-21900),\n",
    "    (application_records_t[\"DAYS_BIRTH\"] < -21900) & (application_records_t[\"DAYS_BIRTH\"]>=-25201)\n",
    "]\n",
    "values3=[\"under 20ties\", \"under 30ties\", \"under 40ties\", \"under 50ties\",\"under 60ties\",\"over 60ties\"]\n",
    "application_records_t[\"DAYS_BIRTH_CATEGORIZED\"]=np.select(conditions3,values3)\n",
    "conditions4=[\n",
    "    (application_records_t[\"DAYS_EMPLOYED\"] > 0),\n",
    "    (application_records_t[\"DAYS_EMPLOYED\"] > 0),\n",
    "    (application_records_t[\"DAYS_EMPLOYED\"] < 0 ) & (application_records_t[\"DAYS_EMPLOYED\"]>=-1825),\n",
    "    (application_records_t[\"DAYS_EMPLOYED\"] < -1825) & (application_records_t[\"DAYS_EMPLOYED\"]>=-3650),\n",
    "    (application_records_t[\"DAYS_EMPLOYED\"] < -3650) & (application_records_t[\"DAYS_EMPLOYED\"]>=-5475),\n",
    "    (application_records_t[\"DAYS_EMPLOYED\"] < -5475),\n",
    "             ]\n",
    "values4=[\"pensioner\",\"no working experience\", \"under 5 years\", \"under 10 years\", \"under 15 years\", \"more than 15 years\"]\n",
    "application_records_t[\"DAYS_EMPLOYED_CATEGORIZED\"]=np.select(conditions4,values4)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "### 3. Enrich credit data and define labels \n",
    "\n",
    "from collections import Counter\n",
    "p=credit_records_t.copy() \n",
    "\n",
    "#add colulmns with val_count(count of statuses), start (first month of loan), end (last month of loan), duration (loan duration)\n",
    "p['val_count']=p.apply(lambda x: Counter(x),axis=1) \n",
    "grouped_id=credit_records_o.groupby('ID')\n",
    "p['start_mth']=grouped_id['MONTHS_BALANCE'].min() #month at which the credit started for client\n",
    "p['end_mth']=grouped_id['MONTHS_BALANCE'].max() #month at which the credit ended for client\n",
    "p['duration']=abs(p['start_mth']-p['end_mth'])+1 #duration of the credit for client\n",
    "\n",
    "#add columns with 0,1,2,3,4,5 statuses count and their ratios per client\n",
    "p['0_count']=p['val_count'].apply(lambda x: x.get('0',0)) \n",
    "p['0_ratio']=p['0_count']/p['duration'] \n",
    "p['1_count']=p['val_count'].apply(lambda x: x.get('1',0)) \n",
    "p['1_ratio']=p['1_count']/p['duration'] \n",
    "p['2_count']=p['val_count'].apply(lambda x: x.get('2',0))\n",
    "p['2_ratio']=p['2_count']/p['duration'] \n",
    "p['3_count']=p['val_count'].apply(lambda x: x.get('3',0))\n",
    "p['3_ratio']=p['3_count']/p['duration'] \n",
    "p['4_count']=p['val_count'].apply(lambda x: x.get('4',0))\n",
    "p['4_ratio']=p['4_count']/p['duration'] \n",
    "p['5_count']=p['val_count'].apply(lambda x: x.get('5',0))\n",
    "p['5_ratio']=p['5_count']/p['duration'] \n",
    "# p['all_late_count']=p['val_count'].apply(lambda x: x.get('0',0)+x.get('1',0)+x.get('2',0)+x.get('3',0)+x.get('4',0)+x.get('5',0)) \n",
    "p['all_late_count']=p['val_count'].apply(lambda x: x.get('2',0)+x.get('3',0)+x.get('4',0)+x.get('5',0)) \n",
    "p['all_late_ratio']=p['all_late_count']/p['duration'] \n",
    "p['all_late_flag']=p['all_late_ratio'].apply(lambda x: 1 if x>0.20 else 0)\n",
    "\n",
    "credit_records_t_label=p.copy()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ### 4. Enrich credit data with Mateusz method\n",
    "# df=credit_records_o.copy() \n",
    "\n",
    "# df[\"MONTHS_BALANCE\"] = df[\"MONTHS_BALANCE\"].abs()\n",
    "\n",
    "# df_last = df.groupby(by=\"ID\")[\"MONTHS_BALANCE\"].min().reset_index(name=\"LAST_RECORD\")\n",
    "# df = pd.merge(df, df_last, on=\"ID\", how=\"left\")\n",
    "\n",
    "# df_all = df.groupby(by=\"ID\")[\"MONTHS_BALANCE\"].count().reset_index(name=\"NUMBER_OF_RECORDS\")\n",
    "# df = pd.merge(df, df_all, on=\"ID\", how=\"left\")\n",
    "\n",
    "# df[\"MONTHS\"] = df[\"MONTHS_BALANCE\"] - df[\"LAST_RECORD\"]\n",
    "\n",
    "# def account_activity(ID, last_record):\n",
    "    \n",
    "#     \"\"\"\n",
    "#     Funkcja zwracająca obecny stan konta klienta.\n",
    "#     Konto aktywne - 1\n",
    "#     Konto nieaktywne - 0\n",
    "#     \"\"\"\n",
    "        \n",
    "#     if last_record == 0:\n",
    "#         active = 1\n",
    "#     else:\n",
    "#         active = 0\n",
    "        \n",
    "        \n",
    "#     return active\n",
    "\n",
    "# df_upgrade = df.copy()\n",
    "# df_upgrade[\"ACTIVE\"] = df_upgrade.apply(lambda df: account_activity(df[\"ID\"], df[\"LAST_RECORD\"]), axis=1)\n",
    "\n",
    "# def month_weight(month, number_of_records):\n",
    "    \n",
    "#     \"\"\"\n",
    "#     Funkcja przyporządkowująca wagę danemu miesiącu (month) z uwzględnieniem liczby wszystkich miesięcy (number_of_months).\n",
    "#     Wagi maleją w sposób liniowy, a ich suma daje 1.\n",
    "#     \"\"\"\n",
    "    \n",
    "#     k = abs(month) + 1\n",
    "#     n = number_of_records\n",
    "    \n",
    "#     if n < 4:\n",
    "#         weight = 0\n",
    "#     elif 4 <= n <= 24:\n",
    "#         weight = -2*k/(n*(n+1))+2/n\n",
    "#     else:\n",
    "#         n = 24\n",
    "#         if k <= 24:\n",
    "#             weight = -2*k/(n*(n+1))+2/n\n",
    "#         else:\n",
    "#             weight = 0\n",
    "              \n",
    "                \n",
    "#     return weight\n",
    "\n",
    "# def status2number(month, status, number_of_records):\n",
    "    \n",
    "#     \"\"\"\n",
    "#     W oparciu o funkcję month_weight, status2number przekształca status z wybranego miesiąca na liczbę z przedziału <-1,1>.\n",
    "\n",
    "#     \"\"\"\n",
    "    \n",
    "#     if month <= 23:\n",
    "#         weight = month_weight(month, number_of_records)\n",
    "\n",
    "#         if status is \"5\":\n",
    "#             value = -1\n",
    "#         elif status is \"X\":\n",
    "#             value = 0\n",
    "#         elif status is \"C\":\n",
    "#             value = 1\n",
    "#         else:\n",
    "#             n = int(status)\n",
    "#             value = 1/2**(n+1)-1\n",
    "#     else:\n",
    "#         weight = 1\n",
    "#         value = 0\n",
    "    \n",
    "    \n",
    "#     return weight * value\n",
    "\n",
    "# df_upgrade[\"PARTIAL_STATUS\"] = df_upgrade.apply(lambda df: status2number(df[\"MONTHS\"], df[\"STATUS\"], df[\"NUMBER_OF_RECORDS\"]), axis=1)\n",
    "\n",
    "# df_status = df_upgrade.groupby(by = \"ID\")[\"PARTIAL_STATUS\"].sum().reset_index(name=\"TOTAL_STATUS\")\n",
    "\n",
    "# df_credit = pd.merge(df_upgrade, df_status, on=\"ID\", how=\"left\")\n",
    "\n",
    "# def good_bad_function(ID, status):\n",
    "    \n",
    "#     \"\"\"\n",
    "#     Funkcja określająca czy dany klient może otrzymać kredyt.\n",
    "#     \"\"\"\n",
    "    \n",
    "#     if status >= 0:\n",
    "#         judgment = 1\n",
    "#     else:\n",
    "#         judgment = 0\n",
    "    \n",
    "    \n",
    "#     return judgment\n",
    "\n",
    "# df_credit[\"GOOD_BAD\"] = df_credit.apply(lambda df: good_bad_function(df[\"ID\"], df[\"TOTAL_STATUS\"]), axis=1)\n",
    "\n",
    "# df_result = df_credit[[\"ID\", \"ACTIVE\", \"TOTAL_STATUS\", \"GOOD_BAD\"]].drop_duplicates().copy()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<>:28: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:30: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:32: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:34: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:36: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:38: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:122: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:124: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:126: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:28: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:30: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:32: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:34: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:36: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:38: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:122: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:124: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:126: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\3048252422.py:28: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "  if status is \"5\":\n",
      "C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\3048252422.py:30: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "  elif status is \"4\":\n",
      "C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\3048252422.py:32: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "  elif status is \"3\":\n",
      "C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\3048252422.py:34: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "  elif status is \"2\":\n",
      "C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\3048252422.py:36: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "  elif status is \"1\":\n",
      "C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\3048252422.py:38: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "  elif status is \"0\":\n",
      "C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\3048252422.py:122: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "  if status is \"5\":\n",
      "C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\3048252422.py:124: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "  elif status is \"X\":\n",
      "C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\3048252422.py:126: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "  elif status is \"C\":\n"
     ]
    }
   ],
   "source": [
    "### 4. Enrich credit data with Matuesz method 2\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "def account_activity(ID, last_record):\n",
    "    \n",
    "    \"\"\"\n",
    "    Funkcja zwracająca obecny stan konta klienta.\n",
    "    Konto aktywne - 1\n",
    "    Konto nieaktywne - 0\n",
    "    \"\"\"\n",
    "        \n",
    "    if last_record == 0:\n",
    "        active = 1\n",
    "    else:\n",
    "        active = 0\n",
    "        \n",
    "        \n",
    "    return active\n",
    "\n",
    "def stat2int(status):\n",
    "    \n",
    "    \"\"\"\n",
    "    text\n",
    "    text\n",
    "    \"\"\"\n",
    "    \n",
    "    if status is \"5\":\n",
    "        value = 6\n",
    "    elif status is \"4\":\n",
    "        value = 5\n",
    "    elif status is \"3\":\n",
    "        value = 4\n",
    "    elif status is \"2\":\n",
    "        value = 3\n",
    "    elif status is \"1\":\n",
    "        value = 2\n",
    "    elif status is \"0\":\n",
    "        value = 1\n",
    "    else:\n",
    "        value = 0\n",
    "    \n",
    "    \n",
    "    return value\n",
    "\n",
    "def delay_calculator(status_list, historical_range, method):\n",
    "    \n",
    "    \"\"\"\n",
    "    text\n",
    "    text\n",
    "    \n",
    "    \"\"\"\n",
    "    \n",
    "    status_list = status_list[:historical_range][::-1]\n",
    "    length = len(status_list)\n",
    "\n",
    "    delay_list = []\n",
    "\n",
    "    for i in range(length):\n",
    "        if i == 0:\n",
    "            delay_list.append(30*status_list[i])\n",
    "        else:\n",
    "            if status_list[i] - 1 == status_list[i-1]:\n",
    "                delay_list.append(30)\n",
    "            elif status_list[i] == status_list[i-1]:\n",
    "                delay_list.append(30*status_list[i])   \n",
    "            else:\n",
    "                delay_list.append(30*status_list[i]) \n",
    "\n",
    "    if method == \"mean\":\n",
    "        delay = np.mean(delay_list)       \n",
    "    elif method == \"median\":\n",
    "        delay = np.median(delay_list)     \n",
    "    elif method == \"median-class\":\n",
    "        value = np.median(delay_list)\n",
    "        if value in delay_list:\n",
    "            delay = value\n",
    "        else:\n",
    "            while value not in delay_list:\n",
    "                value = value - 15\n",
    "            delay = value\n",
    "            \n",
    "    return delay\n",
    "\n",
    "def month_weight(month, number_of_records, mnor, historical_range):\n",
    "    \n",
    "    \"\"\"\n",
    "    Funkcja przyporządkowująca wagę danemu miesiącu (month) z uwzględnieniem liczby wszystkich miesięcy (number_of_months).\n",
    "    Wagi maleją w sposób liniowy, a ich suma daje 1.\n",
    "    \"\"\"\n",
    "    \n",
    "    k = abs(month) + 1\n",
    "    n = number_of_records\n",
    "    \n",
    "    if n < mnor:\n",
    "        weight = 0\n",
    "    elif mnor <= n <= historical_range:\n",
    "        weight = -2*k/(n*(n+1))+2/n\n",
    "    else:\n",
    "        n = historical_range\n",
    "        if k <= historical_range:\n",
    "            weight = -2*k/(n*(n+1))+2/n\n",
    "        else:\n",
    "            weight = 0\n",
    "              \n",
    "                \n",
    "    return weight\n",
    "\n",
    "def status2number(month, status, number_of_records, mnor, historical_range):\n",
    "    \n",
    "    \"\"\"\n",
    "    W oparciu o funkcję month_weight, status2number przekształca status z wybranego miesiąca na liczbę z przedziału <-1,1>.\n",
    "    \n",
    "    \"\"\"\n",
    "    \n",
    "    if month <= historical_range-1:\n",
    "        weight = month_weight(month,\n",
    "                              number_of_records,\n",
    "                              mnor,\n",
    "                              historical_range)\n",
    "\n",
    "        if status is \"5\":\n",
    "            value = -1\n",
    "        elif status is \"X\":\n",
    "            value = 0\n",
    "        elif status is \"C\":\n",
    "            value = 1\n",
    "        else:\n",
    "            n = int(status)\n",
    "            value = 1/2**(n+1)-1\n",
    "    else:\n",
    "        weight = 1\n",
    "        value = 0\n",
    "    \n",
    "    \n",
    "    return weight * value\n",
    "\n",
    "def identify_good(status, threshold):\n",
    "    \n",
    "    \"\"\"\n",
    "    Funkcja określająca czy dany klient może otrzymać kredyt.\n",
    "    \"\"\"\n",
    "    \n",
    "    if status >= threshold:\n",
    "        judgment = 1\n",
    "    else:\n",
    "        judgment = 0\n",
    "    \n",
    "    \n",
    "    return judgment\n",
    "\n",
    "def identify_sufficient(status, threshold, second_threshold):\n",
    "\n",
    "    \"\"\"\n",
    "    \n",
    "    \"\"\"\n",
    "    \n",
    "    if second_threshold <= status < threshold:\n",
    "        judgment = 1\n",
    "    else:\n",
    "        judgment = 0\n",
    "    \n",
    "    \n",
    "    return judgment\n",
    "\n",
    "def main(data_frame,\n",
    "         minimum_number_of_records = 4,\n",
    "         historical_range = 24,\n",
    "         threshold = 0,\n",
    "         second_threshold = 0,\n",
    "         method = \"mean\"):\n",
    "    \n",
    "    \"\"\"\n",
    "    text\n",
    "    text\n",
    "    \n",
    "    \"\"\"\n",
    "    \n",
    "    data_frame[\"MONTHS_BALANCE\"] = data_frame[\"MONTHS_BALANCE\"].abs()\n",
    "    \n",
    "    extra_frame = data_frame.groupby(by=\"ID\")[\"MONTHS_BALANCE\"].min().reset_index(name=\"LAST_RECORD\")\n",
    "    data_frame = pd.merge(data_frame, extra_frame, on=\"ID\", how=\"left\")\n",
    "    \n",
    "    extra_frame = data_frame.groupby(by=\"ID\")[\"MONTHS_BALANCE\"].count().reset_index(name=\"NUMBER_OF_RECORDS\")\n",
    "    data_frame = pd.merge(data_frame, extra_frame, on=\"ID\", how=\"left\")\n",
    "    \n",
    "    data_frame[\"MONTHS\"] = data_frame[\"MONTHS_BALANCE\"] - data_frame[\"LAST_RECORD\"]\n",
    "    \n",
    "\n",
    "    data_frame[\"ACTIVITY\"] = data_frame.apply(lambda df: account_activity(df[\"ID\"],\n",
    "                                                                        df[\"LAST_RECORD\"]), axis=1)\n",
    "    \n",
    "    data_frame[\"INTEGER_STATUS\"] = data_frame.apply(lambda df: stat2int(df[\"STATUS\"]), axis=1)\n",
    "\n",
    "    status_frame = data_frame.groupby(by=\"ID\")[\"INTEGER_STATUS\"].apply(list).reset_index(name=\"STATUS_LIST\")\n",
    "    data_frame = pd.merge(data_frame, status_frame, on=\"ID\", how=\"left\")\n",
    "\n",
    "    data_frame[\"DELAY_PAYMENT\"] = data_frame.apply(lambda df: delay_calculator(df[\"STATUS_LIST\"],\n",
    "                                                                               historical_range,\n",
    "                                                                               method), axis=1)\n",
    "    \n",
    "    data_frame[\"PARTIAL_STATUS\"] = data_frame.apply(lambda df: status2number(df[\"MONTHS\"],\n",
    "                                                                             df[\"STATUS\"],\n",
    "                                                                             df[\"NUMBER_OF_RECORDS\"],\n",
    "                                                                             minimum_number_of_records,\n",
    "                                                                             historical_range), axis=1)\n",
    "    \n",
    "    extra_frame = data_frame.groupby(by = \"ID\")[\"PARTIAL_STATUS\"].sum().reset_index(name=\"TOTAL_STATUS\")\n",
    "    data_frame = pd.merge(data_frame, extra_frame, on=\"ID\", how=\"left\")\n",
    "    \n",
    "    data_frame[\"GOOD\"] = data_frame.apply(lambda df: identify_good(df[\"TOTAL_STATUS\"],\n",
    "                                                                   threshold), axis=1)\n",
    "    \n",
    "    if second_threshold != threshold:\n",
    "        data_frame[\"SUFFICIENT\"] = data_frame.apply(lambda df: identify_sufficient(df[\"TOTAL_STATUS\"],\n",
    "                                                                                   threshold,\n",
    "                                                                                   second_threshold), axis=1)\n",
    "\n",
    "    average_frame = round(data_frame.groupby(by=\"GOOD\")[\"DELAY_PAYMENT\"].mean(), 2).reset_index(name=\"AVERAGE_DELAY\")\n",
    "    data_frame = pd.merge(data_frame,\n",
    "                          average_frame,\n",
    "                          on=\"GOOD\",\n",
    "                          how=\"left\")\n",
    "    \n",
    "    std_frame = round(data_frame.groupby(by=\"GOOD\")[\"DELAY_PAYMENT\"].std(), 2).reset_index(name=\"STD_DELAY\")\n",
    "    data_frame = pd.merge(data_frame,\n",
    "                          std_frame,\n",
    "                          on=\"GOOD\",\n",
    "                          how=\"left\")\n",
    "    \n",
    "    median_frame = round(data_frame.groupby(by=\"GOOD\")[\"DELAY_PAYMENT\"].median(), 2).reset_index(name=\"MEDIAN_DELAY\")\n",
    "    data_frame = pd.merge(data_frame,\n",
    "                          median_frame,\n",
    "                          on=\"GOOD\",\n",
    "                          how=\"left\")\n",
    "    \n",
    "    \n",
    "    return data_frame\n",
    "\n",
    "    # credit_record = pd.read_csv(\"credit_record.csv\")\n",
    "\n",
    "data = main(credit_records_o, threshold = 0, second_threshold = -0.5)\n",
    "data = data[[\"ID\", \"ACTIVITY\", \"GOOD\", \"SUFFICIENT\"]].drop_duplicates(subset=\"ID\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "### 5. Merge app & labelled credit data & enrich it with age, empl in year, income, age, emp bins\n",
    "app_and_credit_label_2=application_records_t.merge(credit_records_t_label,on='ID') #merege of app & credit labelled data\n",
    "# app_and_credit_label_2=app_and_credit_label_2.merge(df_result,on='ID')                 #merege of Mateusz's labells\n",
    "app_and_credit_label_2=app_and_credit_label_2.merge(data,on='ID')                 #merege of Mateusz's labells\n",
    "\n",
    "app_and_credit_label_2['income_bin']=pd.cut(app_and_credit_label_2['AMT_INCOME_TOTAL'],[50000, 75000,100000,150000,200000,250000,300000,float(\"inf\")])\n",
    "app_and_credit_label_2['age']=round((app_and_credit_label_2['DAYS_BIRTH']/365),0)\n",
    "app_and_credit_label_2['age_bin']=pd.cut(app_and_credit_label_2['age'],[-70,-60,-50,-40,-30,-20])\n",
    "app_and_credit_label_2['length_of_empl']=round((app_and_credit_label_2['DAYS_EMPLOYED']/365),0)\n",
    "app_and_credit_label_2['length_of_empl_bin']=pd.cut(app_and_credit_label_2['length_of_empl'],[-30,-20,-10,-5,0])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "#6 DASH APP Profit & Loss Tab\n",
    "\n",
    "from dash import dash, dcc, html, Input, Output, State \n",
    "import dash_bootstrap_components as dbc\n",
    "from dash.exceptions import PreventUpdate\n",
    "import plotly.express as px\n",
    "\n",
    "### START PL tab #############################################\n",
    "\n",
    "client_count=list(range(0,100000,1000))\n",
    "default_prob=[x/100 for x in range(0,10,1)]\n",
    "interest=[x/100 for x in range(0,15,1)]\n",
    "average_credit=list(range(0,100000,1000))\n",
    "\n",
    "PL_controls = dbc.Form([\n",
    "        dbc.Card([dbc.CardHeader('Number of clients'),\n",
    "        dbc.CardBody(dcc.Slider(0, 500000, 1000,value=0,marks=None, tooltip={\"placement\": \"top\", \"always_visible\": True},id='PL_dropdown1'))]),\n",
    "        dbc.Card([dbc.CardHeader('Accepted level of default probability'),\n",
    "        dbc.CardBody(dcc.Slider(0, 0.15, 0.01,value=0,marks=None, tooltip={\"placement\": \"top\", \"always_visible\": True},id='PL_dropdown2'))]),\n",
    "        dbc.Card([dbc.CardHeader('Interest rate'),\n",
    "        dbc.CardBody(dcc.Slider(0, 0.15, 0.01,value=0,marks=None, tooltip={\"placement\": \"top\", \"always_visible\": True},id='PL_dropdown3'))]),\n",
    "        dbc.Card([dbc.CardHeader('Average credit amount'),\n",
    "        dbc.CardBody(dcc.Slider(0, 100000, 1000,value=0,marks=None, tooltip={\"placement\": \"top\", \"always_visible\": True},id='PL_dropdown4'))]),\n",
    "        ])\n",
    "\n",
    "PL_side_bar = html.Div(\n",
    "    [\n",
    "        dbc.CardHeader('Enter parameters'),\n",
    "        html.Br(),\n",
    "        PL_controls\n",
    "        ],\n",
    ")\n",
    "\n",
    "profit_capital_name=dbc.Col(dbc.Alert(\"Profit \\ Capital Return\",color=\"success\"),width={\"size\": 2})\n",
    "profit_income_name=dbc.Col(dbc.Alert(\"Profit \\ Income Ratio\",color=\"success\"),width={\"size\": 2})\n",
    "profit_name=dbc.Col(dbc.Alert(\"Profit\",color=\"success\"),width={\"size\": 2})\n",
    "income_name=dbc.Col(dbc.Alert(\"Income\",color=\"success\"),width={\"size\": 2})\n",
    "loss_name=dbc.Col(dbc.Alert(\"Loss\",color=\"success\"),width={\"size\": 2})\n",
    "\n",
    "profit_capital_val=dbc.Col(dbc.Alert(color=\"success\",id=\"profit_capital\"),width={\"size\": 2})\n",
    "profit_income_val=dbc.Col(dbc.Alert(color=\"success\",id=\"profit_income\"),width={\"size\": 2})\n",
    "profit_val=dbc.Col(dbc.Alert(color=\"success\",id=\"profit_output\"),width={\"size\": 2})\n",
    "income_val=dbc.Col(dbc.Alert(color=\"success\",id=\"income_output\"),width={\"size\": 2},)\n",
    "loss_val=dbc.Col(dbc.Alert(color=\"success\",id=\"loss_output\"),width={\"size\": 2})\n",
    "\n",
    "row1=dbc.Row([profit_capital_name,profit_income_name,profit_name,income_name,loss_name])\n",
    "row2=dbc.Row([profit_capital_val,profit_income_val,profit_val,income_val,loss_val])\n",
    "\n",
    "PL_content=html.Div([row1,row2])\n",
    "PL_tab = html.Div(dbc.Row([dbc.Col(PL_side_bar, width=2),dbc.Col([html.Br(),html.Br(),html.Br(),PL_content])]))\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "#6 DASH APP INTRO TAB\n",
    "\n",
    "##### START INTRO TAB  ######\n",
    "#this defines what are the selections possible in user inputs\n",
    "l1=app_and_credit_label_2.columns[1:17]\n",
    "t1=app_and_credit_label_2.columns[-21:-3]\n",
    "p1=[*range(-60,1,1)]\n",
    "\n",
    "#this defines what are the elements in rows\n",
    "el1=dbc.Col(dcc.Graph(id='graph1'), md=6)\n",
    "el2=dbc.Col(dcc.Graph(id='graph2'), md=6)\n",
    "el3=dbc.Col(dcc.Graph(id='graph3'), md=6)\n",
    "el4=dbc.Col(dcc.Graph(id='graph4'), md=6)\n",
    "\n",
    "#this defines what is in rows\n",
    "row0=dbc.Form([dbc.CardHeader('Select Period'), dcc.RangeSlider(-60, 0, 6, value=[-60, 0], id='start-end')])\n",
    "row1=dbc.Row([el1,el2])\n",
    "row2=dbc.Row([el3,el4])\n",
    "\n",
    "#this defines that controls object is a form consisting of couple cards with couple dash core components called dropdawn. See dash core components here: https://dash.plotly.com/dash-core-components\n",
    "controls = dbc.Form([\n",
    "        dbc.Card([dbc.CardHeader('Select Feature 1'),\n",
    "        dbc.CardBody(dcc.Dropdown(l1,l1,id='l1_drop'))]),\n",
    "        dbc.Card([dbc.CardHeader('Select Feature 2'),\n",
    "        dbc.CardBody(dcc.Dropdown(l1,l1,id='l2_drop'))]),\n",
    "        dbc.Card([dbc.CardHeader('Select target'),\n",
    "        dbc.CardBody(dcc.Dropdown(t1,t1,id='l3_drop'))]),\n",
    "        dbc.Card([dbc.CardHeader('Select target 2'),\n",
    "        dbc.CardBody(dcc.Dropdown(t1,t1,id='l4_drop'))])\n",
    "        ])\n",
    "\n",
    "#this defines that what appears on the left side will have html headings (H2,H5) and controls object\n",
    "sidebar = html.Div(\n",
    "    [\n",
    "        dbc.CardHeader('Select visualisation parameters'),\n",
    "        controls\n",
    "    ],\n",
    ")\n",
    "\n",
    "#this defines that what appears on the right side is built from 3 rows\n",
    "content = html.Div(\n",
    "    [\n",
    "    row0,\n",
    "    row1,\n",
    "    row2,\n",
    "    ],\n",
    ")\n",
    "\n",
    "#this defines that tab1 content is consisting of sidebar and content\n",
    "tab1_content=html.Div(dbc.Row([dbc.Col(sidebar,width=2),dbc.Col(content)]))\n",
    "##### END INTRO TAB  ######"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app '__main__' (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [08/Apr/2022 19:08:42] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [08/Apr/2022 19:08:42] \"GET /assets/style.css?m=1649023007.9403305 HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [08/Apr/2022 19:08:42] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [08/Apr/2022 19:08:42] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [08/Apr/2022 19:08:42] \"GET /_favicon.ico?v=2.3.0 HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [08/Apr/2022 19:08:42] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [08/Apr/2022 19:08:42] \"GET /_dash-component-suites/dash/dcc/async-slider.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [08/Apr/2022 19:08:42] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [08/Apr/2022 19:08:42] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [08/Apr/2022 19:08:42] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py:321: FutureWarning:\n",
      "\n",
      "Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 526, in update_figure\n",
      "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 95, in pivot_table\n",
      "    table = __internal_pivot_table(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 164, in __internal_pivot_table\n",
      "    grouped = data.groupby(keys, observed=observed, sort=sort)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\frame.py\", line 7706, in groupby\n",
      "    return DataFrameGroupBy(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 882, in __init__\n",
      "    grouper, exclusions, obj = get_grouper(\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 877, in get_grouper\n",
      "    raise ValueError(f\"Grouper for '{name}' not 1-dimensional\")\n",
      "ValueError: Grouper for 'CODE_GENDER' not 1-dimensional\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [08/Apr/2022 19:08:42] \""
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "POST /_dash-update-component HTTP/1.1\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\flask\\app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\dash.py\", line 1345, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\User\\anaconda3\\envs\\Dash_Env\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 322, in dash_function\n",
      "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_10572\\561633170.py\", line 289, in conditional_probability\n",
      "    good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
      "UnboundLocalError: local variable 'specific_key' referenced before assignment\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [08/Apr/2022 19:08:42] \"POST /_dash-update-component HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "### 6. DASH APP taking features and 2 tagets to compare targets relation\n",
    "\n",
    "# We use here dash core components https://dash.plotly.com/dash-core-components like graph that shows graph and dropdowns, sliders where users provide input. \n",
    "# We use here dash bootstrap components https://dash-bootstrap-components.opensource.faculty.ai/docs/components/  like tabs, card, form, col, row etc. to organize\n",
    "# everything into 2 tabs, where 1st tab has a side bar and content (rightbar) and all elements are packed into that. \n",
    "\n",
    "# This is just renaming columns to more friendly format so it displays nicely\n",
    "# app_and_credit_label_2.rename(columns={'CODE_GENDER':'Gender', 'FLAG_OWN_CAR': 'Own Car','FLAG_OWN_REALTY':'Own Realty', 'CNT_CHILDREN':'Children Count', 'AMT_INCOME_TOTAL':'Yearly Income','NAME_INCOME_TYPE':'Income Type', 'NAME_EDUCATION_TYPE':'Education Type','NAME_FAMILY_STATUS':'Family Status', 'NAME_HOUSING_TYPE': 'Housing Type','DAYS_BIRTH':'Days Birth', 'DAYS_EMPLOYED':'Days Employed', 'FLAG_MOBIL':'Mobil', 'FLAG_WORK_PHONE':'Work Phone', 'FLAG_PHONE': 'Phone Flag', 'FLAG_EMAIL':'Email.Flag', 'OCCUPATION_TYPE':'Occupation Type', 'CNT_FAM_MEMBERS':'Family Members #','GOOD_BAD':'bad clients 1', 'all_late_flag':'bad clients 2'},inplace=True)\n",
    "\n",
    "#we import here the necessary modules for dash\n",
    "from dash import dash, dcc, html, Input, Output, State\n",
    "from dash._callback_context import callback_context\n",
    "import dash_bootstrap_components as dbc\n",
    "from dash.exceptions import PreventUpdate\n",
    "import plotly.express as px\n",
    "\n",
    "#we set under the app a dash application instance\n",
    "# app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])\n",
    "app = dash.Dash(__name__,external_stylesheets=[dbc.themes.BOOTSTRAP])\n",
    "\n",
    "#Our app is built of tabs. below is exemplary tab. Its made up of 3 rows horizontally and 3 columns in row 2. You can define as many rows and columns as you wish this way you define layout. \n",
    "# All other components like dropdowns, buttons etc. need to go directly into row or column wrappers. You can use dash bootstrap components, dash core controls components and html components. \n",
    "# You can copy ane experiment with the code into either JW_tab, MR_tab, MK_tab,JB_tab\n",
    "\n",
    "JW_tab = html.Div()\n",
    "JB_tab = html.Div()\n",
    "\n",
    "########## START Profit & Loss callback function\n",
    "@app.callback(\n",
    "    Output('profit_capital','children'),\n",
    "    Output('profit_income','children'),\n",
    "    Output('profit_output','children'),\n",
    "    Output('income_output','children'),\n",
    "    Output('loss_output','children'),\n",
    "    Input('PL_dropdown1','value'),\n",
    "    Input('PL_dropdown2','value'),\n",
    "    Input('PL_dropdown3','value'),\n",
    "    Input('PL_dropdown4','value'),prevent_initial_call=True\n",
    "    )\n",
    "def update_figure2(clients,default_probability,interest_rate,credit_amount):\n",
    "        bad_clients=round(clients*default_probability)\n",
    "        good_clients=clients-bad_clients\n",
    "        income=round(good_clients*interest_rate*credit_amount)\n",
    "        loss=round(bad_clients*credit_amount)\n",
    "        profit=income-loss\n",
    "        profit_income=profit/income\n",
    "        profit_capital=profit/(clients*credit_amount)\n",
    "        return profit_capital,profit_income,profit,income,loss\n",
    "########## END Profit & Loss callback function\n",
    "\n",
    "########## START WELCOME PAGE \n",
    "el10=html.Div([\n",
    "\n",
    "    dbc.Card(\n",
    "        [\n",
    "            # dbc.CardImg(src=\"https://raw.githubusercontent.com/infoshareacademy/jdszr6-slytherin_group/master/Slytherin_ClearBG.webp\", top=True,),\n",
    "            dbc.CardBody(\n",
    "                [\n",
    "                    # html.H5(\"SLYTHERIN BANK\", className=\"card_title\"),\n",
    "                html.P(\n",
    "                    \"Welcome in our bank. Please select if you are \"\n",
    "                    \"our client or advisor.\",\n",
    "                    className = \"card_text\",\n",
    "                ),\n",
    "                # dbc.DropdownMenu(\n",
    "                #     label = \"selection\",\n",
    "                #     color = \"success\",\n",
    "                #     children=[\n",
    "                #         dbc.DropdownMenuItem(\"Client\", id=\"client\"),\n",
    "                #         dbc.DropdownMenuItem(\"Advisor\", id=\"advisor\")])\n",
    "                dcc.Dropdown(id=\"special_dropdown\",options=[\"Client\",\"Advisor\"],value=[\"Client\",\"Advisor\"])\n",
    "                ]\n",
    "            )\n",
    "        ],\n",
    "    )\n",
    "    ]\n",
    ")\n",
    "\n",
    "logo_pic=        dbc.Card([\n",
    "            dbc.CardImg(src=\"https://raw.githubusercontent.com/infoshareacademy/jdszr6-slytherin_group/master/Slytherin_ClearBG.webp\", top=True),\n",
    "            dbc.CardBody(html.H5(\"SLYTHERIN BANK\", className=\"card_title\")\n",
    "            )]) \n",
    "\n",
    "MR_tab=html.Div(dbc.Row([dbc.Col([html.Br(),logo_pic],width=2),dbc.Col([html.Br(),el10],width=2)]))\n",
    "\n",
    "# MR_tab = (dbc.Row([dbc.Col(dbc.Card(dbc.CardImg(src=\"https://raw.githubusercontent.com/infoshareacademy/jdszr6-slytherin_group/master/Slytherin_ClearBG.webp\", top=True,)),width=2),dbc.Col(el10)]))\n",
    "\n",
    "######### END WELCOME PAGE\n",
    "\n",
    "########## START SELECTION PAGE \n",
    "#dropdown for client/advisor list\n",
    "data_frame = app_and_credit_label_2\n",
    "list_ca_tab1 = dbc.Form([\n",
    "       # NAME_INCOME_TYPE 4\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"NAME_INCOME_TYPE\"].unique(),\n",
    "        placeholder = \"NAME_INCOME_TYPE\",\n",
    "        id = \"income_type\"),\n",
    "        # NAME_EDUCATION_TYPE 5\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"NAME_EDUCATION_TYPE\"].unique(),\n",
    "        placeholder = \"NAME_EDUCATION_TYPE\",\n",
    "        id = \"education_type\"),\n",
    "    # NAME_FAMILY_STATUS 6\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"NAME_FAMILY_STATUS\"].unique(),\n",
    "        placeholder = \"NAME_FAMILY_STATUS\",\n",
    "        id = \"family_status\"),\n",
    "    # FLAG_EMAIL 10\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"FLAG_EMAIL\"].unique(),\n",
    "        placeholder = \"FLAG_EMAIL\",\n",
    "        id = \"email\"),\n",
    "    # OCCUPATION_TYPE 11\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"OCCUPATION_TYPE\"].unique(),\n",
    "        placeholder = \"OCCUPATION_TYPE\",\n",
    "        id = \"occupation\"),\n",
    "    # MEMBERS 13\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"CNT_FAM_MEMBERS_CATEGORIZED\"].unique(),\n",
    "        placeholder = \"MEMBERS\",\n",
    "        id = \"members\"),\n",
    "    # AGE 14\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"DAYS_BIRTH_CATEGORIZED\"].unique(),\n",
    "        placeholder = \"AGE\",\n",
    "        id = \"age\"),\n",
    "    # INCOME 16\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"AMT_INCOME_TOTAL_CATEGORIZED\"].unique(),\n",
    "        placeholder = \"INCOME\",\n",
    "        id = \"income\")\n",
    "    ])\n",
    "list_ca_tab2 = dbc.Form([\n",
    "    # CODE_GENDER 1\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"CODE_GENDER\"].unique(),\n",
    "        #[\"M\", \"F\"],\n",
    "        placeholder = \"CODE_GENDER\",\n",
    "        id = \"gender\"),\n",
    "    # FLAG_OWN_CAR 2\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"FLAG_OWN_CAR\"].unique(),\n",
    "        placeholder = \"FLAG_OWN_CAR\",\n",
    "        id = \"car\"),\n",
    "    # FLAG_OWN_REALTY 3\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"FLAG_OWN_REALTY\"].unique(),\n",
    "        placeholder = \"FLAG_OWN_REALTY\",\n",
    "        id = \"realty\"),\n",
    "    # NAME_HOUSING_TYPE 7\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"NAME_HOUSING_TYPE\"].unique(),\n",
    "        placeholder = \"NAME_HOUSING_TYPE\",\n",
    "        id = \"housing_type\"),\n",
    "    # FLAG_WORK_PHONE 8\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"FLAG_WORK_PHONE\"].unique(),\n",
    "        placeholder = \"FLAG_WORK_PHONE\",\n",
    "        id = \"work_phone\"),\n",
    "    # FLAG_PHONE 9\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"FLAG_PHONE\"].unique(),\n",
    "        placeholder = \"FLAG_PHONE\",\n",
    "        id = \"phone\"),\n",
    "    # CHILDREN 12\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"CNT_CHILDREN_CATEGORIZED\"].unique(),\n",
    "        placeholder = \"CHILDREN\",\n",
    "        id = \"kids\"),\n",
    "    # YEARS_EMPLOYED 15\n",
    "    dcc.Dropdown(\n",
    "        data_frame[\"DAYS_EMPLOYED_CATEGORIZED\"].unique(),\n",
    "        placeholder = \"YEARS_EMPLOYED\",\n",
    "        id = \"employed\"),\n",
    "    ])\n",
    "@app.callback(\n",
    "    Output(\"textarea_id5\", \"children\"), #first output goes to tab Decision Client\n",
    "    Output(\"textarea_id3\", \"children\"), #second output goes to tab Decision Page Advisor\n",
    "    Output(\"textarea_id4\", \"children\"), #second output goes to tab Decision Page Advisor\n",
    "    Input(\"gender\", \"value\"),\n",
    "    Input(\"car\",\"value\"),\n",
    "    Input(\"realty\", \"value\"),\n",
    "    Input(\"income_type\", \"value\"),\n",
    "    Input(\"education_type\", \"value\"),\n",
    "    Input(\"family_status\", \"value\"),\n",
    "    Input(\"housing_type\", \"value\"),\n",
    "    Input(\"work_phone\", \"value\"),\n",
    "    Input(\"phone\", \"value\"),\n",
    "    Input(\"email\", \"value\"),\n",
    "    Input(\"occupation\", \"value\"),\n",
    "    Input(\"kids\", \"value\"),\n",
    "    Input(\"members\", \"value\"),\n",
    "    Input(\"age\", \"value\"),\n",
    "    Input(\"employed\", \"value\"),\n",
    "    Input(\"income\", \"value\")\n",
    "\n",
    "#     ['ID',\n",
    "#  'CODE_GENDER',\n",
    "#  'FLAG_OWN_CAR',\n",
    "#  'FLAG_OWN_REALTY',\n",
    "#  'CNT_CHILDREN',\n",
    "#  'AMT_INCOME_TOTAL',\n",
    "#  'NAME_INCOME_TYPE',\n",
    "#  'NAME_EDUCATION_TYPE',\n",
    "#  'NAME_FAMILY_STATUS',\n",
    "#  'NAME_HOUSING_TYPE',\n",
    "#  'DAYS_BIRTH',\n",
    "#  'DAYS_EMPLOYED',\n",
    "#  'FLAG_WORK_PHONE',\n",
    "#  'FLAG_PHONE',\n",
    "#  'FLAG_EMAIL',\n",
    "#  'OCCUPATION_TYPE',\n",
    "#  'CNT_FAM_MEMBERS',\n",
    "#  'CNT_CHILDREN_CATEGORIZED',\n",
    "#  'CNT_FAM_MEMBERS_CATEGORIZED',\n",
    "#  'AMT_INCOME_TOTAL_CATEGORIZED',\n",
    "#  'DAYS_BIRTH_CATEGORIZED',\n",
    "#  'DAYS_EMPLOYED_CATEGORIZED',\n",
    ")\n",
    "def dash_function(gender,car,realty,income_type,education_type, family_status, housing_type,\n",
    "                  work_phone, phone,email, occupation, children, members, age, employed, income):\n",
    "    personal_data = {'CODE_GENDER': gender,\n",
    "                     'FLAG_OWN_CAR': car,\n",
    "                     'FLAG_OWN_REALTY': realty,\n",
    "                     'NAME_INCOME_TYPE': income_type,\n",
    "                     'NAME_EDUCATION_TYPE': education_type,\n",
    "                     'NAME_FAMILY_STATUS': family_status,\n",
    "                     'NAME_HOUSING_TYPE': housing_type,\n",
    "                     'FLAG_WORK_PHONE': work_phone,\n",
    "                     'FLAG_PHONE': phone,\n",
    "                     'FLAG_EMAIL': email,\n",
    "                     'OCCUPATION_TYPE': occupation,\n",
    "                     'CNT_CHILDREN_CATEGORIZED': children,\n",
    "                     'CNT_FAM_MEMBERS_CATEGORIZED': members,\n",
    "                     'DAYS_BIRTH_CATEGORIZED': age,\n",
    "                     'DAYS_EMPLOYED_CATEGORIZED': employed,\n",
    "                     'AMT_INCOME_TOTAL_CATEGORIZED': income\n",
    "    }\n",
    "    z=personal_data.copy()\n",
    "    main_features = ['OCCUPATION_TYPE',\n",
    "                     'DAYS_BIRTH_CATEGORIZED',\n",
    "                     'AMT_INCOME_TOTAL_CATEGORIZED',\n",
    "                     'FLAG_EMAIL',\n",
    "                     'NAME_FAMILY_STATUS',\n",
    "                     'NAME_EDUCATION_TYPE',\n",
    "                     'NAME_INCOME_TYPE',\n",
    "                     'CNT_FAM_MEMBERS_CATEGORIZED']\n",
    "    extra_features = ['FLAG_OWN_CAR',\n",
    "                      'FLAG_OWN_REALTY',\n",
    "                      'NAME_HOUSING_TYPE',\n",
    "                      'FLAG_WORK_PHONE',\n",
    "                      'FLAG_PHONE',\n",
    "                      'CNT_CHILDREN_CATEGORIZED',\n",
    "                      'DAYS_BIRTH_CATEGORIZED',\n",
    "                      'CODE_GENDER']\n",
    "    main_data = {feature: personal_data[feature] for feature in main_features}\n",
    "    extra_data = {feature: personal_data[feature] for feature in extra_features}\n",
    "    \n",
    "    def conditional_probability(data_frame, personal_data, split_method, threshold):\n",
    "        \n",
    "        \"\"\"\n",
    "        TEXT\n",
    "        TEXT\n",
    "        \"\"\"\n",
    "        \n",
    "        if split_method == \"standard\":\n",
    "            good_clients = data_frame[(data_frame[\"GOOD\"] == 1) | (data_frame[\"SUFFICIENT\"] == 1)]\n",
    "            bad_clients = data_frame[(data_frame[\"GOOD\"] == 0) & (data_frame[\"SUFFICIENT\"] == 0)]\n",
    "        elif split_method == \"good\":\n",
    "            good_clients = data_frame[data_frame[\"GOOD\"] == 1]\n",
    "            bad_clients = data_frame[data_frame[\"GOOD\"] == 0]\n",
    "        elif split_method == \"sufficient\":\n",
    "            data_frame = data_frame[data_frame[\"GOOD\"] == 0]\n",
    "            good_clients = data_frame[data_frame[\"SUFFICIENT\"] == 1]\n",
    "            bad_clients = data_frame[data_frame[\"SUFFICIENT\"] == 0]\n",
    "        \n",
    "        for i in range(1, len(personal_data)+1):\n",
    "            records = 0\n",
    "\n",
    "            for key, value in personal_data.items():\n",
    "                conditional_records = len(data_frame[data_frame[key] == value])\n",
    "                if conditional_records > records:\n",
    "                    records = conditional_records\n",
    "                    specific_key = key\n",
    "                    specific_value = value\n",
    "                    \n",
    "            good_records = len(good_clients[good_clients[specific_key] == specific_value])\n",
    "            bad_records = len(bad_clients[bad_clients[specific_key] == specific_value])\n",
    "            client_records = good_records + bad_records\n",
    "\n",
    "            if client_records >= threshold and bad_records > 0:\n",
    "                personal_data = {key:personal_data[key] for key in personal_data if key!=specific_key}\n",
    "                good_clients = good_clients[good_clients[specific_key] == specific_value]\n",
    "                bad_clients = bad_clients[bad_clients[specific_key] == specific_value]\n",
    "                probability = round(bad_records/(bad_records + good_records), 5)\n",
    "            else:\n",
    "                break\n",
    "\n",
    "            \n",
    "        return probability, personal_data\n",
    "\n",
    "    def executor(data_frame, personal_data, main_data, extra_data, split_method = \"standard\", threshold = 1000, second_threshold = 500):\n",
    "        result = conditional_probability(data_frame, main_data, split_method, threshold)\n",
    "        probability, data = result\n",
    "        if len(data) != 0:\n",
    "            result = conditional_probability(data_frame, main_data, split_method, second_threshold)\n",
    "            new_probability, new_data = result\n",
    "        if len(new_data) < len(data) and new_probability <= probability:\n",
    "            probability = new_probability\n",
    "            data = new_data\n",
    "            extra_data = dict(extra_data, **data)\n",
    "        for key, value in extra_data.items():\n",
    "            single_dict = {key: value}\n",
    "            new_probability = conditional_probability(data_frame, dict(main_data, **single_dict),split_method, second_threshold)[0]\n",
    "        if new_probability <= probability:\n",
    "            probability = new_probability\n",
    "            main_data = dict(main_data, **single_dict)\n",
    "        return probability\n",
    "    personal_data = data_frame.drop([\"ID\", \"GOOD\", \"SUFFICIENT\"], axis=1).sample().to_dict(\"record\")[0]\n",
    "    x = conditional_probability(data_frame, main_data, \"standard\", 1000)[0]\n",
    "    y = executor(data_frame, personal_data, main_data, extra_data)\n",
    "\n",
    "    inflation = 0.1\n",
    "    def decision(probability, inflation):\n",
    "        if probability >= 0.04:\n",
    "            interest_rate = round(((1 + inflation/12)/(1 - probability) - 1)* 100,2)\n",
    "            statement_cl = \"We are not able to provide you with an offer. Please contact client advisor.\"\n",
    "            statement_ad = \"Client above accepted default probability treshold. Accept only with interest rate {}%.\".format(interest_rate)\n",
    "        else:\n",
    "            interest_rate = round(((1 + inflation/12)/(1 - probability) - 1)* 100,2)\n",
    "            statement_cl = \"We can offer you loan with: {}% interest rate.\".format(interest_rate)\n",
    "            statement_ad = \"Client within accepted default probability treshold. Propose interest rate {}%.\".format(interest_rate)\n",
    "        return statement_cl,statement_ad\n",
    "    \n",
    "    z_cl,z_ad=decision(y,0.1)\n",
    "           \n",
    "    return [html.H6(str(\"Decision: {}\".format(z_cl)))],[html.H6(str(\"Probability of default based on key characteriscs: {}\".format(x))),html.H6(str(\"Probability of default based on all characteriscs: {}\".format(y)))],[html.H6(str(\"Decision: {}\".format(z_ad)))]\n",
    "\n",
    "\n",
    "\n",
    "el11= dbc.Card([dbc.CardHeader(\"Key Characteristics\"),\n",
    "            list_ca_tab1,\n",
    "        ])\n",
    "el12= dbc.Card([dbc.CardHeader(\"Optional Characteristics\"),\n",
    "            list_ca_tab2,\n",
    "        ]) \n",
    "\n",
    "button= dbc.Card([html.Button(\"Apply\", id=\"apply_button\")])\n",
    "\n",
    "list_of_content = html.Div([dbc.Row([\n",
    "    dbc.Col([html.Br(),logo_pic],width=2),\n",
    "        dbc.Col([dbc.Row([\n",
    "            dbc.Col([html.Br(),el11],width=2),\n",
    "            dbc.Col([html.Br(),el12],width=2)]),\n",
    "            dbc.Col([html.Br(),button],width={\"size\": 2, \"offset\": 1})])])\n",
    "            ])\n",
    "\n",
    "# This callback enables switch of tabs with apply button on selection page and dropdown menu on welcome page\n",
    "@app.callback(\n",
    "    Output(\"tabs\", \"active_tab\"),\n",
    "    Input(\"apply_button\", \"n_clicks\"),\n",
    "    Input(\"special_dropdown\", \"value\"))\n",
    "def tab_select(click,dropdown):\n",
    "    ctx = callback_context\n",
    "    if not ctx.triggered:\n",
    "        triger_id = None\n",
    "        return \"tab2\"\n",
    "    else:\n",
    "        triger_id = ctx.triggered[0]['prop_id'].split('.')[0]\n",
    "        print(triger_id)\n",
    "    if triger_id==\"apply_button\" and click:\n",
    "        if dropdown=='Client':\n",
    "            return \"tab4\"\n",
    "        elif dropdown=='Advisor':\n",
    "            return \"tab5\"\n",
    "        else:\n",
    "            return \"tab3\"\n",
    "    elif triger_id==\"special_dropdown\":\n",
    "        if dropdown == \"Client\":\n",
    "            return \"tab3\"\n",
    "        elif dropdown == \"Advisor\":\n",
    "            return \"tab3\"\n",
    "######## END SELECTION PAGE\n",
    "\n",
    "######## START DECISION PAGE ADVISOR  #########\n",
    "el13 =html.Div(\n",
    "[      \n",
    "        dbc.Card([dbc.CardHeader('Highlevel Default Probability \\ Exact Default Probability'),dbc.CardBody(id=\"textarea_id3\")]),\n",
    "        dbc.Card([dbc.CardHeader('Credit Guidelines'),dbc.CardBody(id='textarea_id4')]),\n",
    "        dbc.Card([dbc.CardHeader('Put down your notes here'),dbc.CardBody(\n",
    "        [dcc.Textarea(\n",
    "            id=\"textarea_id1\",\n",
    "            value=\"Notes\",\n",
    "            style={\"height\": 100},\n",
    "                ),\n",
    "            dcc.Clipboard(\n",
    "            target_id=\"textarea_id2\",\n",
    "            title=\"copy\",\n",
    "            style={\n",
    "                \"display\": \"inline-block\",\n",
    "                \"fontSize\": 20,\n",
    "                \"verticalAlign\": \"top\",\n",
    "                    },\n",
    "                    )\n",
    "                                ])\n",
    "        ]),\n",
    "        dbc.Card([\n",
    "            dbc.CardHeader('Download final offer here'), dbc.CardBody(dbc.Button(id='btn1',\n",
    "            children=[html.I(className=\"fa fa-download mr-1\"), \"Download offer\"],\n",
    "            color=\"info\",\n",
    "            className=\"mt-1\"\n",
    "        ),)\n",
    "                    ]),\n",
    "        dcc.Download(id=\"download-component1\"),\n",
    "])\n",
    "\n",
    "MK_tab=html.Div(dbc.Row([dbc.Col([html.Br(),logo_pic],width=2),dbc.Col([html.Br(),el13],width=2)]))\n",
    "    \n",
    "@app.callback(\n",
    "    Output(\"download-component1\", \"data\"),\n",
    "    Input(\"btn1\", \"n_clicks\"),\n",
    "    prevent_initial_call=True,\n",
    ")\n",
    "def func(n_clicks):\n",
    "    return dict(content=\"Credit card approved\", filename=\"offer.txt\")\n",
    "\n",
    "@app.callback(\n",
    "    Output('output-container-range-slider', 'children'),\n",
    "    [Input('my-range-slider', 'value')])\n",
    "def update_output(value):\n",
    "    return 'You have selected \"{}\"'.format(value)\n",
    "@app.callback(\n",
    "    Output('textarea-state-example-output', 'children'),\n",
    "    Input('textarea-state-example-button', 'n_clicks'),\n",
    "    State('textarea-state-example', 'value')\n",
    ")\n",
    "def update_output(n_clicks, value):\n",
    "    if n_clicks > 0:\n",
    "        return 'You have entered: \\n{}'.format(value)       \n",
    "######### END DECISION PAGE ADVISOR ##########\n",
    "\n",
    "\n",
    "##### START DECISION PAGE CLIENT ######\n",
    "from dash import dash_table\n",
    "\n",
    "df_to_dict_exp = pd.DataFrame([[\"abc@mail.com\",\"123 456 789\",\"2000-01-01\",\"Sales staff\",\n",
    "                                \"high income\",\"Working\",\"Higher education\",\"Married\",\"2+1\"]],\n",
    "                                columns = [\"E-Mail\",\"Phone\",\"Birth date\",\"Occupation type\",\"Yearly income\",\n",
    "                                \"Income type\",\"Education type\",\"Family status\",\"Family members\"])\n",
    "# dict_exp = df_to_dict_exp.to_dict()\n",
    "# table_tab\n",
    "# dcit_exp=z.to_dict\n",
    "# print(dict_exp)\n",
    "el14 = html.Div(\n",
    "[      \n",
    "        dbc.Card([dbc.CardHeader('Our proposal for credit'),dbc.CardBody(id='textarea_id5')]),\n",
    "        dbc.Card([dbc.CardHeader('Put down your notes here'),dbc.CardBody(\n",
    "        [dcc.Textarea(\n",
    "            id=\"textarea_id6\",\n",
    "            value=\"Notes\",\n",
    "            style={\"height\": 100},\n",
    "                ),\n",
    "            dcc.Clipboard(\n",
    "            target_id=\"textarea_id7\",\n",
    "            title=\"copy\",\n",
    "            style={\n",
    "                \"display\": \"inline-block\",\n",
    "                \"fontSize\": 20,\n",
    "                \"verticalAlign\": \"top\",\n",
    "                    },\n",
    "                    )\n",
    "                                ])\n",
    "        ]),\n",
    "        dbc.Card([\n",
    "            dbc.CardHeader('Download final offer here'), dbc.CardBody(dbc.Button(id='btn8',\n",
    "            children=[html.I(className=\"fa fa-download mr-1\"), \"Download offer\"],\n",
    "            color=\"info\",\n",
    "            className=\"mt-1\"\n",
    "        ),)\n",
    "                    ]),\n",
    "        dcc.Download(id=\"download-component2\"),\n",
    "])\n",
    "\n",
    "JW_tab=html.Div(dbc.Row([dbc.Col([html.Br(),logo_pic],width=2),dbc.Col([html.Br(),el14],width=2)]))\n",
    "##### END DECISION PAGE CLIENT ######\n",
    "\n",
    "# Below defines that TABS object is built from Tabs and Tab components from dash bootstrap components https://dash-bootstrap-components.opensource.faculty.ai/docs/components/. Essentially\n",
    "# its a list of tabs that the app will be divided into. Its easy to remove a tab (just remove element of the list) or add another tab just copy the line and change label.\n",
    "TABS = dbc.Tabs(\n",
    "    [\n",
    "        # dbc.Tab(example_tab, label=\"Data Eploration\"), #data exploration\n",
    "        # dbc.Tab(example_tab, label=\"Application simulator\"), #yes or no card \n",
    "        dbc.Tab(MR_tab, label=\"Welcome Page\",tab_id=\"tab2\"),  #tab for MR to to experiment with dash\n",
    "        dbc.Tab(list_of_content, label=\"Selection Page\",tab_id=\"tab3\"),\n",
    "        # dbc.Tab(example_tab, label=\"Example tab\" ),\n",
    "        dbc.Tab(JW_tab, label=\"Decision Page Client\",tab_id=\"tab4\"),  #tab to for JW to experiment with dash\n",
    "        dbc.Tab(MK_tab, label=\"Decision Page Advisor\",tab_id=\"tab5\"),  #tab for MK to to experiment with dash\n",
    "        # dbc.Tab(JB_tab, label=\"JB tab\"),  #tab for JB to to experiment with dash\n",
    "        dbc.Tab(PL_tab, label=\"Profit & Loss simulator\",tab_id=\"tab6\"), #board simulation \n",
    "        dbc.Tab(tab1_content, label=\"Explore Historical Data\",tab_id=\"tab1\"), #information on project\n",
    "    ], id=\"tabs\"\n",
    ")\n",
    "\n",
    "#this defines that app layout will consiste of tabs object\n",
    "app.layout = html.Div([TABS,dcc.Store(id='intermediate-value')])\n",
    "\n",
    "####### START INTRO TAB CALLBACK\n",
    "#this code binds defines inputs and outputs. \n",
    "@app.callback(\n",
    "    Output('graph1', 'figure'),\n",
    "    Output('graph2', 'figure'),\n",
    "    Output('graph3', 'figure'),\n",
    "    Output('graph4', 'figure'),\n",
    "    Input('l1_drop', 'value'),\n",
    "    Input('l2_drop','value'),\n",
    "    Input('l3_drop','value'),\n",
    "    Input('l4_drop','value'),\n",
    "    [Input('start-end', 'value')]\n",
    "    )\n",
    "#this is function that is called by dash whenever user changes input in my case it draws charts \n",
    "def update_figure(l1_val,l2_val,t_val,t_val1,ss):\n",
    "    lst=[]\n",
    "    data=app_and_credit_label_2[(app_and_credit_label_2['start_mth']>=ss[0]) & (app_and_credit_label_2['start_mth']<=ss[1])]\n",
    "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val,aggfunc='mean',margins=True).round(4)\n",
    "    lst.append(px.bar(df,barmode='group',text_auto=True,title=\"{} bad clients % by {} and {}\".format(t_val,l1_val,l2_val))),\n",
    "    lst.append(px.imshow(df,color_continuous_scale='RdBu_r',text_auto=\".2%\",title=\"{} bad clients % by {} and {}\".format(t_val,l1_val,l2_val))),\n",
    "    df=pd.pivot_table(data,index=l1_val,columns=l2_val,values=t_val1,aggfunc='mean',margins=True).round(4)\n",
    "    lst.append(px.bar(df,barmode='group',text_auto=True,title=\"{} bad clients % by {} and {}\".format(t_val1,l1_val,l2_val))),\n",
    "    lst.append(px.imshow(df,color_continuous_scale='RdBu_r',text_auto=True,title=\"{} bad clients % by {} and {}\".format(t_val1,l1_val,l2_val)))\n",
    "    for i in range(len(lst)):\n",
    "        lst[i].update_layout(transition_duration=500)\n",
    "        lst[i].layout.yaxis.tickformat = ',.2%' #show things as percentage with 2 decimal places\n",
    "    lst[2].update_xaxes(type='category') #heatmap charts weren't working correclty withotu making axes categorical\n",
    "    return lst\n",
    "####### END INTRO TAB CALLBACK\n",
    "\n",
    "\n",
    "#command below will start the web application (in output cell there should be address which needs to be copied into webrowser to access app, likely: http://127.0.0.1:8050/ )\n",
    "if __name__ == '__main__':\n",
    "    app.run_server()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>z</th>\n",
       "      <th>b</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   z  b\n",
       "1  1  2"
      ]
     },
     "execution_count": 36,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pd.DataFrame({'z':'1','b':'2'},index=['1'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'df_credit' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\User\\OneDrive\\Desktop\\Kurs2\\jdszr6-slytherin_group\\PYTHON_project\\Master\\Credit_Approval3.ipynb Cell 11'\u001b[0m in \u001b[0;36m<cell line: 5>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/User/OneDrive/Desktop/Kurs2/jdszr6-slytherin_group/PYTHON_project/Master/Credit_Approval3.ipynb#ch0000010?line=1'>2</a>\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mnumpy\u001b[39;00m \u001b[39mas\u001b[39;00m \u001b[39mnp\u001b[39;00m\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/User/OneDrive/Desktop/Kurs2/jdszr6-slytherin_group/PYTHON_project/Master/Credit_Approval3.ipynb#ch0000010?line=3'>4</a>\u001b[0m \u001b[39m#files merging\u001b[39;00m\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/Users/User/OneDrive/Desktop/Kurs2/jdszr6-slytherin_group/PYTHON_project/Master/Credit_Approval3.ipynb#ch0000010?line=4'>5</a>\u001b[0m new_file\u001b[39m=\u001b[39mpd\u001b[39m.\u001b[39mmerge(application_records_t,df_credit,on\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mID\u001b[39m\u001b[39m\"\u001b[39m,how\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39minner\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/User/OneDrive/Desktop/Kurs2/jdszr6-slytherin_group/PYTHON_project/Master/Credit_Approval3.ipynb#ch0000010?line=5'>6</a>\u001b[0m new_file\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/User/OneDrive/Desktop/Kurs2/jdszr6-slytherin_group/PYTHON_project/Master/Credit_Approval3.ipynb#ch0000010?line=7'>8</a>\u001b[0m new_file\u001b[39m.\u001b[39mdrop(\u001b[39m\"\u001b[39m\u001b[39mFLAG_OWN_CAR\u001b[39m\u001b[39m\"\u001b[39m, axis\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mcolumns\u001b[39m\u001b[39m\"\u001b[39m, inplace\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m)\n",
      "\u001b[1;31mNameError\u001b[0m: name 'df_credit' is not defined"
     ]
    }
   ],
   "source": [
    "### 7. Matrix \n",
    "import numpy as np\n",
    "\n",
    "#files merging\n",
    "new_file=pd.merge(application_records_t,df_credit,on=\"ID\",how=\"inner\")\n",
    "new_file\n",
    "\n",
    "new_file.drop(\"FLAG_OWN_CAR\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"FLAG_OWN_REALTY\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"CNT_CHILDREN\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"AMT_INCOME_TOTAL\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"NAME_HOUSING_TYPE\", axis=\"columns\", inplace=True)\n",
    "\n",
    "new_file.drop(\"CODE_GENDER\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"DAYS_BIRTH\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"DAYS_EMPLOYED\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"FLAG_WORK_PHONE\", axis=\"columns\", inplace=True)\n",
    "\n",
    "new_file.drop(\"FLAG_PHONE\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"CNT_FAM_MEMBERS\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"MONTHS_BALANCE\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"STATUS\", axis=\"columns\", inplace=True)\n",
    "\n",
    "new_file.drop(\"LAST_RECORD\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"MONTHS\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"ACTIVE\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"PARTIAL_STATUS\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"TOTAL_STATUS\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"CNT_CHILDREN_CATEGORIZED\", axis=\"columns\", inplace=True)\n",
    "new_file.drop(\"DAYS_EMPLOYED_CATEGORIZED\", axis=\"columns\", inplace=True)\n",
    "\n",
    "#matrix preparation\n",
    "\n",
    "matrix=new_file.groupby([\"OCCUPATION_TYPE\",\"DAYS_BIRTH_CATEGORIZED\",\"AMT_INCOME_TOTAL_CATEGORIZED\",\"FLAG_EMAIL\",\"NAME_FAMILY_STATUS\",\"NAME_EDUCATION_TYPE\",\n",
    "                     \"NAME_INCOME_TYPE\", \"CNT_FAM_MEMBERS_CATEGORIZED\",\"GOOD_BAD\"]).count()\n",
    "\n",
    "matrix[\"cumsum\"]=matrix.groupby([\"OCCUPATION_TYPE\",\"DAYS_BIRTH_CATEGORIZED\",\"AMT_INCOME_TOTAL_CATEGORIZED\",\"FLAG_EMAIL\",\"NAME_FAMILY_STATUS\",\"NAME_EDUCATION_TYPE\",\n",
    "                     \"NAME_INCOME_TYPE\", \"CNT_FAM_MEMBERS_CATEGORIZED\"]).sum()[\"ID\"]\n",
    "\n",
    "matrix[\"Percentage\"]=matrix[\"ID\"]/matrix[\"cumsum\"]*100\n"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "8fac594bfae6525c0c41b4041d2d72effa188cc8ead05f81b1fab2bb098927fb"
  },
  "kernelspec": {
   "display_name": "Python 3.9.7 ('base')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
